plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/node/workspace/openclaw/Hawthorn"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/cellar-door/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]